### ISSUE TITLE
How create a handlerException with jooby?

### ISSUE THREAD

**Issue by Khwesten** [danielfireman/acessoatodos#19]

**Comment by danielfireman** [comment]
As soon as you finish your commits, I'll introduce an example. That will make things easier.

**Comment by danielfireman** [comment]
Using [Whoops](https://github.com/jooby-project/jooby/tree/master/jooby-whoops) for now. It is quite nice.

This is issue was fixed by commit 81e968f74f404ae6669f5a5729c76a28ee0438da
